---
title: "perference_network"
author: "Kianté Fernandez"
date: "3/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(tidyverse)
library(qgraph)
library(igraph)
library(bootnet)
library(RColorBrewer)
library(NetworkComparisonTest)
library(huge)
library(boot)
library(EGAnet)
```

```{r}
setsize_9_desc_data <- read_csv("~/Documents/OSU/Karmarkar_2021_subset_choice/multi_select/many-item-single-choice/data/summary_files/setsize-9_desc-data.csv")
#we need to read in all the liking data for each subject
temp = list.files(path = "~/Documents/OSU/Karmarkar_2021_subset_choice/multi_select/many-item-single-choice/data/subject_files", pattern="liking_ratings", full.names = T)

myfiles <- vector(mode = "list", length = length(temp))
for (idx in seq_along(myfiles)){
  myfiles[[idx]] = readr::read_csv(temp[[idx]])
  # temp = read_csv(temp[idx])
  # myfiles <- rbind(myfiles, temp)
}

rating_data <-plyr::ldply(myfiles, data.frame) 
rating_data$rating <- rating_data$rating + 4

rating_network <- rating_data %>% 
  select(stimulus, rating) %>% 
  pivot_wider(names_from = stimulus, values_from = rating) %>% 
  map(unlist) %>% 
  map(as.numeric)

rating_network <- list.cbind(rating_network)

# colnames(rating_network)[order(names(rating_network))]

cor_x1 <- cor(as.data.frame(rating_network))
cor_x1 <- matrix(Matrix::nearPD(cor_x1, corr=TRUE, maxit = 500 )$mat, ncol = 80)
cor_x1 <- (cor_x1 + t(cor_x1)) / 2 # make symmetric
# colnames(cor_x1) <- colnames(rating_matrix)

test_net <-EGAnet::EGA(rating_network, n = 49, model = "glasso", algorithm = "walktrap",corr = "pearson")
boot_test <- EGAnet::bootEGA(rating_network,
                             iter = 100,
                             type = "resampling",
                             corr = "pearson",
                             n = 49,
                             model = "glasso",
                             algorithm = "walktrap",
                             ncores = 8, typicalStructure = T)


#get ready for network
# rating_network <- huge.npn(rating_network, npn.func = "shrinkage", npn.thresh = NULL, verbose = TRUE)
```

```{r load self_control data}
# helper functions for working with lists
list.do <- function(.data, fun, ...) {
  do.call(what = fun, args = as.list(.data), ...)
}
list.cbind <- function(.data) {
  list.do(.data, "cbind")
}
temp = list.files(path = "/Users/kiantefernandez/Downloads/Self Control", pattern="exp_rating_data", full.names = T)

myfiles <- vector(mode = "list", length = length(temp))
for (idx in seq_along(myfiles)){
  myfiles[[idx]] = readr::read_csv(temp[[idx]])
  # temp = read_csv(temp[idx])
  # myfiles <- rbind(myfiles, temp)
}
rating_data <-plyr::ldply(myfiles, data.frame) 

table(factor(rating_data$PicID))
table(factor(rating_data$SubjectNumber))

names(rating_data)

rating_network <- rating_data %>% 
  select(PicID, TasteRating) %>% 
  pivot_wider(names_from = PicID, values_from = TasteRating) %>% 
  map(unlist) %>% 
  map(as.numeric)

rating_matrix <- list.cbind(rating_network)

cor_x1 <- cor(na.omit(as.data.frame(rating_matrix)))
cor_x1 <- matrix(Matrix::nearPD(cor_x1, corr=TRUE, maxit = 500 )$mat, ncol = 139)
cor_x1 <- (cor_x1 + t(cor_x1)) / 2 # make symmetric
# colnames(cor_x1) <- colnames(rating_matrix)

test_net <-EGAnet::EGA(cor_x1, n = 139, model = "glasso", algorithm = "walktrap",corr = "pearson")


boot_test <- EGAnet::bootEGA(as.dataframe(rating_matrix),
                             iter = 10,
                             type = "resampling",
                             corr = "pearson",
                             n = 139,
                             model = "glasso",
                             algorithm = "walktrap",
                             ncores = 8, typicalStructure = T)


```

```{r}
library(ggplot2)
library(ggcorrplot)
library(corrplot)

# calulate the correlations
r <- cor(rating_network, use="complete.obs")
corrplot(r, method="color", type="upper", order="hclust")

ggcorrplot(r, 
           type = "upper")

TEST <- correlation::correlation(rating_network)
corrplot(M, type="upper", order="hclust")

x <- TEST[order(TEST$r, decreasing = T),]
min(TEST$r)
```

```{r}

test <- Matrix::nearPD(cor(rating_network))
########################
#Network estimation
#Gaussian graphical models
Perference_self_control <- estimateNetwork(rating_network, 
                           default = "ggmModSelect",
                           start = "empty",
                           considerPerStep = "all",
                           nCores = 8,
                           stepwise = TRUE,
                           verbose = FALSE)

ega_rating    <- EGA(rating_network, model = "glasso", plot.EGA = TRUE) 

```


